[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cmp[cli]>=0.0.1",
    "httpx>=0.28.1",
    "langchain-community>=0.3.30",
]
